### ISSUE TITLE
Rmarkdown format

### ISSUE THREAD

**Issue by markziemann** [kogamanya/SLE712-assessment3#1]
For the Rmarkdown to work, it needs to have a header as well as code blocks.

---
title: "Assignment 3 part 1"
author: "Kingsley"
date: "18/05/2020"
output: html_document
---
## Question 1
question1: Read in the file, making the gene accession numbers the row names. 
Show a table of values for the first six genes.
```{r,download}
download.file("https://raw.githubusercontent.com/markziemann/SLE712_files/master/bioinfo_asst3_part1_files/gene_expression.tsv",
              destfile = "gene_expression.tsv")
```
 i use the download.file command to import files from GitHub 
 And then read in R making sure the first columns is set as the row names and headers are recongnized 
 so as to show a table of values for the first six genes 
using the head command to check if the gene has been imported properly 
 by showing a table of values for the first six genes
and to check data structure 

```{r,import_read}
gene <- read.table("gene_expression.tsv",header = TRUE , stringsAsFactors = FALSE , row.names = 1)
head(gene)
str(gene)
```

**Comment by kogamanya** [comment]
Issues on Rmarkdown resolved
